export const logoData = [
  {
    id: 1,
    logo: "../../assets/img/sass.png",
    alt: "sass",
    name: "Sass",
  },
  // {
  //   id: 2,
  //   logo: "../../assets/img/bootstrap.png",
  //   alt: "bootstrap",
  //   name: "Bootstrap",
  // },
  {
    id: 2,
    logo: "../../assets/img/tailwind_css.png",
    alt: "tailwind",
    name: "Tailwind CSS",
  },
  {
    id: 4,
    logo: "../../assets/img/javascript.webp",
    alt: "javascript",
    name: "JavaScript",
  },
  {
    id: 5,
    logo: "../../assets/img/react.webp",
    alt: "reactjs",
    name: "ReactJs",
  },
  {
    id: 6,
    logo: "../../assets/img/react-native-1.svg",
    alt: "reactNative",
    name: "React Native",
  },
  {
    id: 7,
    logo: "../../assets/img/expo.svg",
    alt: "expo",
    name: "EXPO",
  },
  {
    id: 8,
    logo: "../../assets/img/typescript.webp",
    alt: "typescript",
    name: "TypeScript",
  },
  {
    id: 9,
    logo: "../../assets/img/nextjs.png",
    alt: "nextjs",
    name: "NextJs",
  },
  {
    id: 10,
    logo: "../../assets/img/vitejs-logo.svg",
    alt: "vite",
    name: "Vite",
  },
  // {
  //   id: 11,
  //   logo: "../../assets/img/wordpress.png",
  //   alt: "wordpress",
  //   name: "WordPress",
  // },
  {
    id: 11,
    logo: "../../assets/img/aws.webp",
    alt: "aws",
    name: "AWS",
  },
  {
    id: 12,
    logo: "../../assets/img/nodeJs.png",
    alt: "nodejs",
    name: "NodeJs",
  },
];
